apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd3
  namespace: default
  labels:
    app: httpd3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd3
    spec:
      containers:
        - name: httpd3
          image: httpd:2.4
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: httpd3-persistent-storage
              mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: httpd3-persistent-storage
        vsphereVolume:
         volumePath: "[Datastore-12] kubevols/kubeVolume"
         fsType: ext4
---
kind: Service
apiVersion: v1
metadata:
  name: httpd3
  namespace: default
spec:
  selector:
    app: httpd3
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
      app: httpd3
  type: LoadBalancer
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: httpd3
    annotations:
      kubernetes.io/ingress.class: nginx
  spec:
    rules:
      - host: httpd3.norsys.group
        http:
          paths:
            - path: /
              backend:
                serviceName: httpd3
                servicePort: 80
